Risolvere il seguente sistema lineare:

x1   +  x2 = 4

2\*x1+  x2 = 1

In [1]:
solve(matrix(c(1, 2, 1, 1), nrow=2), c(4, 1))

[1] -3  7

# Esercizio 1

Costruire due matrici M ed N di cinque colonne; M deve contenere i numeri da 1 a 15 ed N da 16 a 35. Costruire, se possibile, una matrice di 5 colonne che abbia come righe le righe di entrambe le matrici. Utilizzando M ed N, è possibile creare una matrice che abbia come colonne le colonne di entrambe le matrici?

In [2]:
M <- matrix(1:15, ncol=5)
N <- matrix(16:35, ncol=5)
M
N

[,1] [,2] [,3] [,4] [,5]
[1,] 1    4    7    10   13  
[2,] 2    5    8    11   14  
[3,] 3    6    9    12   15

[,1] [,2] [,3] [,4] [,5]
[1,] 16   20   24   28   32  
[2,] 17   21   25   29   33  
[3,] 18   22   26   30   34  
[4,] 19   23   27   31   35

In [3]:
rbind(M, N)

[,1] [,2] [,3] [,4] [,5]
[1,]  1    4    7   10   13  
[2,]  2    5    8   11   14  
[3,]  3    6    9   12   15  
[4,] 16   20   24   28   32  
[5,] 17   21   25   29   33  
[6,] 18   22   26   30   34  
[7,] 19   23   27   31   35

In [4]:
cbind(M, N)

ERROR: Error in cbind(M, N): number of rows of matrices must match (see arg 2)


# Esercizio 2

1. Costruire due matrici quadrate A e B di dimensione 3X3 costituite da un campione di numeri estratti casualmente senza riposizionamento tra i primi 50 interi
2. Calcolare il prodotto elemento per elemento e “righe per colonne”
3. Scegliere un vettore b di 3 elementi e risolvere il sistema lineare Ax=b che ne deriva

In [5]:
A <- matrix(sample(1:50, 9), nrow=3)
B <- matrix(sample(1:50, 9), nrow=3)
A
B

[,1] [,2] [,3]
[1,] 22   38   40  
[2,]  2   27   16  
[3,] 50   23   34

[,1] [,2] [,3]
[1,] 36   25   45  
[2,]  1   24   42  
[3,]  7    9   32

In [6]:
A*B
A%*%B

[,1] [,2] [,3]
[1,] 792  950  1800
[2,]   2  648   672
[3,] 350  207  1088

[,1] [,2] [,3]
[1,] 1110 1822 3866
[2,]  211  842 1736
[3,] 2061 2108 4304

In [7]:
b <- c(23, 2, 51)
solve(A, b)

[1]  0.99362953 -0.03756942  0.06419471

# Esercizio 3

Siano dati i seguenti studenti con relativi punteggi di esame:

* Nomi : Luigi, Francesca, Carlo, Alberto, Nicola, Giovanna
* Voti : 28, 18, 25, 21, 30 , 22
* ripetizioni esame : 3, 2, 1, 1, 2, 2


1. Inserire i dati in una matrice R 6x2, avendo come colonne voti e numero di ripetizioni dell’esame
2. Assegnare i nomi di riga; per le colonne utilizzate “voto” e “ripetizioni”
3. Determinare (non a mano) il numero di studenti nelle tre fasce di voto: \<22, 23-26, 27>
4. Aggiungere una colonna “fascia” alla matrice, in cui inseriamo 3 per gli studenti in fascia 18-22, 2 per gli studenti in fascia 23-26 e 1 per quelli in fascia 27-30
5. Stampare le frequenze relative delle fasce di studenti

In [8]:
voti <- c(28, 18, 25, 21, 30, 22)
ripetizioni <- c(3, 2, 1, 1, 2, 2)
esami <- cbind(voti, ripetizioni)
rownames(esami) <- c("Luigi", "Francesca", "Carlo", "Alberto", "Nicola", "Giovanna")
esami

voti ripetizioni
Luigi     28   3          
Francesca 18   2          
Carlo     25   1          
Alberto   21   1          
Nicola    30   2          
Giovanna  22   2

In [9]:
length(voti[voti<=22])
length(voti[voti>=23 & voti<=26])
length(voti[voti>=27])

[1] 3

[1] 1

[1] 2

In [10]:
fascia <- rep(3, times=length(voti)) - (voti>=23) - (voti>=27)
esami <- cbind(esami, fascia)
esami

voti ripetizioni fascia
Luigi     28   3           1     
Francesca 18   2           3     
Carlo     25   1           2     
Alberto   21   1           3     
Nicola    30   2           1     
Giovanna  22   2           3

In [12]:
table(fascia)

fascia
1 2 3 
2 1 3 

Utilizzando le definizioni (non le formule predefinite di R)

6. Determinare la media campionaria dei voti e del numero di ripetizioni d’esame
7. Verificare che la somma degli scarti dalla media sia 0
8. Determinare la varianza campionaria dei voti e del numero di ripetizioni
9. Esiste una correlazione positiva tra i voti ed il numero di ripetizioni?

In [17]:
mediavoti <- sum(voti)/length(voti)
mediavoti
mediarip <- sum(ripetizioni)/length(ripetizioni)
mediarip

[1] 24

[1] 1.833333

In [21]:
sum(voti - mediavoti)

[1] 0

In [26]:
varvoti <- sum((voti - mediavoti)**2)/(length(voti)-1)
varvoti
varrip <- sum((ripetizioni - mediarip)**2)/(length(ripetizioni)-1)
varrip

[1] 20.4

[1] 0.5666667

In [27]:
corrvotirip <- sum((voti - mediavoti)*(ripetizioni - mediarip))/((length(voti)-1)*sqrt(varvoti)*sqrt(varrip))
corrvotirip

[1] 0.3529412

# Esercizio 4

1. Scaricare il il dataset dataset1.csv
2. Importare il dataset e creare un vettore che contenga i dati della prima colonna:

In [34]:
dati <- read.csv(file = "dataset1.csv") 
eta <- dati$Eta
voti <- dati$Voti
tentativi <- dati$Tentativi

a questo punto avrete un vettore eta, uno voti e uno tentativi contenenti 45222 valori numerici.

Per i vettori “voti”, “tentativi” ed “eta”:

3. Calcolare media e mediana utilizzando le funzioni viste in aula durante la teoria
4. Calcolare varianza
5. Calcolare la deviazione standard
6. Calcolare il primo e il terzo quartile
7. il vettore “tentativi” è un pelino strano? Perchè?

In [33]:
mean(voti)
median(voti)
mean(tentativi)
median(tentativi)
mean(eta)
median(eta)

[1] 24.99886

[1] 25

[1] 10

[1] 10

[1] 38.58745

[1] 37

In [39]:
var(voti)
var(tentativi)
var(eta)

[1] 4.144043

[1] 0

[1] 175.6928

In [41]:
sd(voti)
sd(tentativi)
sd(eta)

[1] 2.035692

[1] 0

[1] 13.25491

In [43]:
quantile(voti, 0.25)
quantile(voti, 0.75)
quantile(tentativi, 0.25)
quantile(tentativi, 0.75)
quantile(eta, 0.25)
quantile(eta, 0.75)

25% 
 24

75% 
 26

25% 
 10

75% 
 10

25% 
 28

75% 
 47